# Generated by Django 5.2.7 on 2025-10-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_todo_duration_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='duration',
        ),
    ]
