# Generated by Django 5.2.7 on 2025-10-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_todo_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
    ]
