# Generated by Django 5.2.7 on 2025-10-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_todo_reminder_task_id_alter_todo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='list_type',
        ),
    ]
